# Generated by Django 3.2.9 on 2021-11-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=200)),
                ('depDirect', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employeers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('foto', models.FileField(null=True, upload_to='upload/')),
                ('position', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('age', models.IntegerField()),
                ('departament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employ', to='testDRF.depart')),
            ],
        ),
    ]
